### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by michel5** [platelminto/java-bittrex-2#1]
Be resigned to this version because it is the latest version but I get a problem here.

Exception in thread "Timer 0" java.lang.StringIndexOutOfBoundsException: String index out of range: -10

Any idea what is going wrong here?

**Comment by platelminto** [comment]
Bittrex's v2 API is not fully developed yet, and the in-progress version i used to build this wrapper has since changed. I have contacted them to ask at what point v2 is currently at, but for now use the v1.1 wrapper.

**Comment by michel5** [comment]
I must use this wrapper then?

https://github.com/platelminto/java-bittrex

**Comment by platelminto** [comment]
Correct

**Comment by michel5** [comment]
TY!
