### ISSUE TITLE
BuyLimit \ TradeBuy with "ConditionType" and "Target"

### ISSUE THREAD

**Issue by trojanhost** [platelminto/java-bittrex-2#3]
i use bittrex API 1.1 and 2.0 for trading client (Delphi).
how use method BuyLimit with "ConditionType" and "Target" parameters?

this sample dont work? :

https://bittrex.com/api/v2.0/auth/market/tradebuy?&nonce=1502481723&MarketName=BTC-BCC&OrderType=LIMIT&Quantity=0.0005&Rate=0.10271362101&TimeInEffect=IMMEDIATE_OR_CANCEL&ConditionType=GREATER_THAN&Target=0.10271362101&__RequestVerificationToken=********

**Comment by platelminto** [comment]
Do not use v2 as it does not work - please read the readme file. Use v1.1, linked in the readme, as that has been tested and does indeed work with a released version of the Bittrex API.

**Comment by trojanhost** [comment]
v1.1 dont have "ConditionType" and "Target" in order :(

**Comment by trojanhost** [comment]
v1.1 dont have "ConditionType" and "Target" :(
official web site bittrex.com for buy \ sell use v2.0 only..

**Comment by platelminto** [comment]
v2.0 doesn't yet exist, so that functionality must either not yet be available through their API or is present in some way through the existing place order functions.
